import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";
import "react-datepicker/dist/react-datepicker.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} min-h-screen w-full bg-[#020617] relative`}
      >
        <div
          className="absolute inset-0 z-invert-0"
          style={{
            backgroundImage: `radial-gradient(circle 500px at 50% 100px, rgba(139,92,246,0.4), transparent)`,
            pointerEvents: "none",
          }}
        />
        <div className="absolute inset-0 z-invert-1">{children}</div>
      </body>
    </html>
  );
}
